#!/bin/bash

echo "=================================="
echo "SOLANA PROGRAM DEPLOYMENT TO DEVNET"
echo "=================================="
echo ""
echo "IMPORTANT: The program is NOT yet deployed to devnet!"
echo ""
echo "The program ID has been updated to: DKkV5YimB3gjBLhtLMGRzkv5PeR4FZ9PXjMLHwd9umdr"
echo "But it needs to be deployed before the frontend can interact with it."
echo ""
echo "To deploy the program, you need to run these commands on a system with Solana/Anchor CLI installed:"
echo ""
echo "Option 1: Using Anchor (recommended):"
echo "-------------------------------------"
echo "cd /path/to/your/project"
echo "anchor build"
echo "anchor deploy --program-keypair new-program-keypair.json"
echo ""
echo "Option 2: Using Solana CLI directly:"
echo "------------------------------------"
echo "cd programs/fractional_vault"
echo "cargo build-bpf"
echo "solana program deploy --program-id ../../new-program-keypair.json target/deploy/fractional_vault.so --url devnet"
echo ""
echo "Prerequisites:"
echo "- Solana CLI installed (https://docs.solana.com/cli/install-solana-cli-tools)"
echo "- Anchor CLI installed (npm i -g @coral-xyz/anchor-cli)"
echo "- A funded Solana wallet (at least 2-3 SOL for deployment)"
echo "- Wallet configured for devnet: solana config set --url devnet"
echo ""
echo "The keypair file 'new-program-keypair.json' has been generated and contains the private key for the program."
echo ""
echo "After deployment, the program will be live at:"
echo "https://explorer.solana.com/address/DKkV5YimB3gjBLhtLMGRzkv5PeR4FZ9PXjMLHwd9umdr?cluster=devnet" 