[package]
name = "fractional_vault"
version = "0.1.0"
edition = "2021"

[lib]
name = "fractional_vault"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.26.0", features = ["init-if-needed"] }
anchor-spl = "0.26.0"
spl-token = "3.3.0"
spl-associated-token-account = "1.0.5"
borsh = "0.9.3"
solana-program = "=1.16.27"
